x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "10"
      max-size: "100m"

services:
  workspace:
    container_name: ${COMPOSE_PROJECT_NAME:-default}-workspace-container
    restart: unless-stopped
    env_file: .env
    build:
      context: ./docker/workspace
      args:
        USERNAME: ${USERNAME:-vscode}
        USER_GROUP_NAME: ${USER_GROUP_NAME:-workspace}
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    tty: true
    volumes:
      - ./docker/server:/home/${USERNAME:-vscode}/workspace/server:cached
    working_dir: /home/${USERNAME:-vscode}/workspace
    <<: *logging
