name: Build Docker simple server image CI

on:
  push:
    branches: [ "master", "dev" ]
    paths:
      - "docker/server/**"
      - ".github/workflows/build-server.yml"

# Dockerのログイン
# 環境変数の設定
# Dockerイメージのビルド・タグ付け・イメージのプッシュ
jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v3

      - name: Build & push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          
          export DOCKER_IMAGE_TAG=${GITHUB_SHA::7}
          export DOCKER_IMAGE="${{ secrets.DOCKER_USERNAME }}/simple-server:${DOCKER_IMAGE_TAG}"
          
          docker build . --file ./prod/server/Dockerfile --tag ${DOCKER_IMAGE}
          docker tag ${DOCKER_IMAGE} ${{ secrets.DOCKER_USERNAME }}/simple-server:latest

          docker push ${DOCKER_IMAGE}
          docker push ${{ secrets.DOCKER_USERNAME }}/simple-server:latest
